version: '3.8'

services:
  redis:
    image: redis
    container_name: redis-server
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ypicqjct
      RABBITMQ_DEFAULT_PASS: mS1bIMsqzyBD08HRliydkru8QZI8rDXH
    networks:
      - backend
    
  webapi:
    image: dockerredistest:dev
    build:
      context: .
      dockerfile: DockerRedisTest/Dockerfile
    depends_on:
      - redis
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5005:8080"
    volumes:
      - ./web-api/appsettings.json:/app/appsettings.json
    networks:
      - backend
    links:
      - rabbitmq
networks:
  backend:
    driver: bridge   